version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:7.0.4
    command: mongod --quiet
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  redis:
    container_name: redis
    image: redis:alpine3.19
    ports:
      - "6379:6379"

  celery-image:
    container_name: celery-image
    build:
      context: worker
    entrypoint: celery
    command: -A app worker -Q image_process,dev -c 4
    depends_on:
      - redis
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/db"
      REDIS_URI: "redis://redis:6379/0"

  celery-slice:
    container_name: celery-slice
    build:
      context: worker
    entrypoint: celery
    command: -A app worker -Q slice -c 2
    depends_on:
      - redis
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/db"
      REDIS_URI: "redis://redis:6379/0"
      MIN_ZOOM: 1
      MAX_ZOOM: 17
      
  server:
    container_name: server
    build:
      context: server
    restart: unless-stopped
    command: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 --bind 0.0.0.0:80 run:app
    ports:
      - "5000:80"
    environment:
      FLASK_PORT: 80
      MONGO_URI: "mongodb://mongo:27017/db"
      REDIS_URI: "redis://redis:6379/0"
      DEBUG: False
    depends_on:
      - celery-image
      - celery-slice
      - redis
      - mongo
    volumes:
      - ./worker/map_samples:/map_samples


  client:
    container_name: client
    build: client/
    ports:
      - "3000:80"
    depends_on:
      - server

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    ports:
      - "3001:80"
    volumes:
      - ./nginx/templates/:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
      CLIENT: "client:80"
      SERVER: "server:80"
      PORT: "80"
    depends_on:
      - client
      - server
