name: "7. App is ready"

on:
  push:
    branches:
      - main

jobs:
  check_app_is_ready:
    name: "Проверка наличия тега 1.0"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        name: Check out current commit
        with:
          fetch-depth: 0
    
      - name: check
        run: |
          TAG="1.0"
          if [ $(git tag -l "${TAG}") ]; then
            echo "::notice::Тег ${TAG} найден"
          else
            echo "::error::Тег ${TAG} не найден"
            exit 1
          fi
